### ISSUE TITLE
How to create my own sdf file for testing purposes ?

### ISSUE THREAD

**Issue by phongnhhn92** [angeladai/sgnn#1]
Hello,
First of all, I would like to say thanks for uploading the code and data. However, I would like to test model performance on the real scan using my mobile phone.

My plan is to use a smartphone to capture both RGB and depth images and then convert them to a projective truncated signed distance function (TSDF) volume. At the moment, I am using [this tool](https://github.com/andyzeng/tsdf-fusion-python) to do it. However, the output of this tool is a mesh in ply format. 

Therefore, I would like to ask how can I convert any mesh to the .sdf files which you are using in your network for further testing?

**Comment by angeladai** [comment]
The data generation for creating TSDFs is provided in https://github.com/angeladai/sgnn/tree/master/datagen/GenerateScans

**Comment by phongnhhn92** [comment]
Hi, thanks for your reply !
I have manage to build the GenerateScans project but I am receiving the error that there is a missing ply file as can be seen here: 
![1](https://user-images.githubusercontent.com/11288381/77077352-c884a500-69fd-11ea-8b21-83fcb84646c8.PNG)
So the program is looking for region0__0.sdfs.reduced.ply of the scene 17DRP5sb8fy. 
However, when i tried to download the scene 17DRP5sb8fy, I can not find this file in the **region_segmentations** folder.
In the **region_segmentations** folder, I only see 10 sets of separate regions like this: 
![2](https://user-images.githubusercontent.com/11288381/77083545-5e243280-6a06-11ea-9f46-d03c227da194.PNG)

How can i create those region0__0.sdfs.reduced.ply that you have been using in your program ? Thanks !

**Comment by santhu937** [comment]
@phongnhhn92  Can u please provide any two test scenes since I can't download the around 90 GB of test data.

Thank You

**Comment by santhu937** [comment]
@phongnhhn92 can u please tell the steps to test on my own data which is of .ply format.

Thank you

**Comment by LiuXinchen1997** [comment]
@phongnhhn92 Hi, did u run the project GenerateScans successfully to convert mesh to .sdfs?
I meet a error: “mLibCore.h”: No such file or directory	GenerateScans	J:\Python\sgnn-master\datagen\GenerateScans\src\mLibInclude.h
![image](https://user-images.githubusercontent.com/22675008/103475062-ef716380-4de4-11eb-85ce-87ace34af8c4.png)
Could u know how to solve this error? :-)

**Comment by phongnhhn92** [comment]
> @phongnhhn92 Hi, did u run the project GenerateScans successfully to convert mesh to .sdfs? I meet a error: “mLibCore.h”: No such file or directory GenerateScans J:\Python\sgnn-master\datagen\GenerateScans\src\mLibInclude.h ![image](https://user-images.githubusercontent.com/22675008/103475062-ef716380-4de4-11eb-85ce-87ace34af8c4.png) Could u know how to solve this error? :-)

Hi, it has been a while but I think these are the libraries that you need. https://githubplus.com/niessner/mLib
I think we need to manually include those header files in the VSCode.

**Comment by phongnhhn92** [comment]
> @phongnhhn92 Can u please provide any two test scenes since I can't download the around 90 GB of test data.
> 
> Thank You

Hi, you can use this [tool](https://github.com/andyzeng/tsdf-fusion-python) to generate the mesh that you have. Unfortunately, I still have no idea how to generate the sdf files to test my own mesh :D

**Comment by ferbrjan** [comment]
> @phongnhhn92 Hi, did u run the project GenerateScans successfully to convert mesh to .sdfs? I meet a error: “mLibCore.h”: No such file or directory GenerateScans J:\Python\sgnn-master\datagen\GenerateScans\src\mLibInclude.h ![image](https://user-images.githubusercontent.com/22675008/103475062-ef716380-4de4-11eb-85ce-87ace34af8c4.png) Could u know how to solve this error? :-)

Hi, 

I wrote down some helpful tips on how to install the generatescans VS project. Hopefuly it helps someone to progress a bit. :-)

[sgnn help.txt](https://github.com/angeladai/sgnn/files/7800626/sgnn.help.txt)

Good luck,

Jan

**Comment by ferbrjan** [comment]
> Hi, thanks for your reply ! I have manage to build the GenerateScans project but I am receiving the error that there is a missing ply file as can be seen here: ![1](https://user-images.githubusercontent.com/11288381/77077352-c884a500-69fd-11ea-8b21-83fcb84646c8.PNG) So the program is looking for region0__0.sdfs.reduced.ply of the scene 17DRP5sb8fy. However, when i tried to download the scene 17DRP5sb8fy, I can not find this file in the **region_segmentations** folder. In the **region_segmentations** folder, I only see 10 sets of separate regions like this: ![2](https://user-images.githubusercontent.com/11288381/77083545-5e243280-6a06-11ea-9f46-d03c227da194.PNG)
> 
> How can i create those region0__0.sdfs.reduced.ply that you have been using in your program ? Thanks !

Hi,

I made some progress and maybe managed to solved the issue here. First of all, the mp-rooms_trainval.txt should look something like this:

17DRP5sb8fy_room0
17DRP5sb8fy_room1
17DRP5sb8fy_room2
17DRP5sb8fy_room3
17DRP5sb8fy_room4
17DRP5sb8fy_room5
17DRP5sb8fy_room6
17DRP5sb8fy_room7
17DRP5sb8fy_room8
17DRP5sb8fy_room9

Then you need to create a new .ply file from the original region0.ply and reduce it's "size". I did this in meshlab according to this link: https://help.sketchfab.com/hc/en-us/articles/205852789-MeshLab-Decimating-a-model. (the number of faces was  put to 10 000 as a first try, might be changed later on) I named the new region0.ply as region0.reduced.ply. (you can also change the original file but then you need to change the code to look for correct file (scansdirectory.h line 34))

Now I started the program and it is processing the region0...!!!!

<img width="892" alt="Snímek obrazovky 2022-01-04 v 13 33 51" src="https://user-images.githubusercontent.com/74875970/148059820-c0f78352-ddd1-4cd5-a2a4-c32b20b607ff.png">

Gonna update you later on the results :)))

**Comment by phongnhhn92** [comment]
@ferbrjan That's great update ! I hope to hear the good news from you, my friend. This sure helps a lot of people including me.

**Comment by ferbrjan** [comment]
> @ferbrjan That's great update ! I hope to hear the good news from you, my friend. This sure helps a lot of people including me.

Good news, Some .sdf and .knw files were generated! Try it out my friend! :-)

**Comment by angeladai** [comment]
> Hi, thanks for your reply ! I have manage to build the GenerateScans project but I am receiving the error that there is a missing ply file as can be seen here: ![1](https://user-images.githubusercontent.com/11288381/77077352-c884a500-69fd-11ea-8b21-83fcb84646c8.PNG) So the program is looking for region0__0.sdfs.reduced.ply of the scene 17DRP5sb8fy. However, when i tried to download the scene 17DRP5sb8fy, I can not find this file in the **region_segmentations** folder. In the **region_segmentations** folder, I only see 10 sets of separate regions like this: ![2](https://user-images.githubusercontent.com/11288381/77083545-5e243280-6a06-11ea-9f46-d03c227da194.PNG)
> 
> How can i create those region0__0.sdfs.reduced.ply that you have been using in your program ? Thanks !

The *reduced.ply files are the same mesh files but without any face attributes (vertices and face indices are identical to the original plys; meshlab can produce them)

**Comment by dongshengLiu** [comment]
@ferbrjan Thank you my brother, based on your discussion I can generate some .sdf and .knw files on Matterport3D/17DRP5sb8fy dataset. But how can I generate .sdf and .kw files for my own dataset?

**Comment by ferbrjan** [comment]
> @ferbrjan Thank you my brother, based on your discussion I can generate some .sdf and .knw files on Matterport3D/17DRP5sb8fy dataset. But how can I generate .sdf and .kw files for my own dataset?

@dongshengLiu I wrote you an email to the address associated with your github account! 😇

**Comment by dongshengLiu** [comment]
> > @ferbrjan Thank you my brother, based on your discussion I can generate some .sdf and .knw files on Matterport3D/17DRP5sb8fy dataset. But how can I generate .sdf and .kw files for my own dataset?
> 
> @dongshengLiu I wrote you an email to the address associated with your github account! 😇

I received the email, thank you for your selfless help, I will read your paper carefully and try to solve my problem, thanks again~

**Comment by command-z-z** [comment]
> > @ferbrjan Thank you my brother, based on your discussion I can generate some .sdf and .knw files on Matterport3D/17DRP5sb8fy dataset. But how can I generate .sdf and .kw files for my own dataset?
> 
> @dongshengLiu I wrote you an email to the address associated with your github account! 😇

@ferbrjan I am currently trying this code and encountering some difficulties, and I also want to know  how to generate .sdf and .kw files for my own dataset? Can you help me? Thanks:)

**Comment by command-z-z** [comment]
I have rewritten the code to implement testing using tsdf grid in .npy format. If subsequent workers need in the future, happy to contact me:)

**Comment by iyinlin** [comment]
> > @ferbrjan Thank you my brother, based on your discussion I can generate some .sdf and .knw files on Matterport3D/17DRP5sb8fy dataset. But how can I generate .sdf and .kw files for my own dataset?谢谢我的兄弟，根据你的讨论，我可以在 Matterport3D/17DRP5sb8fy 数据集上生成一些 .sdf 和 .knw 文件。但是如何为我自己的数据集生成 .sdf 和 .kw 文件？
> 
> @dongshengLiu I wrote you an email to the address associated with your github account! 😇 我给您写了一封电子邮件到与您的 github 帐户关联的地址！ 😇

Hello friend, I am a beginner and I have encountered the same problem. Could you please provide me with some reference or assistance. Thank you very much!

**Comment by xxyLA** [comment]
> > @phongnhhn92 Hi, did u run the project GenerateScans successfully to convert mesh to .sdfs? I meet a error: “mLibCore.h”: No such file or directory GenerateScans J:\Python\sgnn-master\datagen\GenerateScans\src\mLibInclude.h ![image](https://user-images.githubusercontent.com/22675008/103475062-ef716380-4de4-11eb-85ce-87ace34af8c4.png) Could u know how to solve this error? :-)
> 
> Hi,
> 
> I wrote down some helpful tips on how to install the generatescans VS project. Hopefuly it helps someone to progress a bit. :-)
> 
> [sgnn help.txt](https://github.com/angeladai/sgnn/files/7800626/sgnn.help.txt)
> 
> Good luck,
> 
> Jan

Hey bro, I followed the help to build but encountered the following problem, could you provide some tips for assistance? Thanks a lot!
D3D11Utility.cpp    C3861 : 'D3DCompileFromFile' : identifier not found.
