### ISSUE TITLE
The outputs are not correct in testing

### ISSUE THREAD

**Issue by XLechter** [angeladai/sgnn#3]
Hi, I use the provided pretrained model in testing, but the output sdf looks strange. I print the output_sdf as follows:
**[ 0 | 20 ] ['Z6MFQCViBuw_room7__0__'] (128, 416, 384)    input_dim [128 416 384]
output_sdf [tensor([[  0,   0,   0,   0],
        [  0,   0,   1,   0],
        [  0,   1,   0,   0],
        ...,
        [ 47, 374, 327,   0],
        [ 47, 375, 326,   0],
        [ 47, 375, 327,   0]]), tensor([[-0.0468],
        [-0.0468],
        [-0.0468],
        ...,
        [-0.0468],
        [-0.0468],
        [-0.0468]], device='cuda:0')]**
It seems all the values in the output are the same **-0.0468**, so the output ply file is empty.
The only changes I made to the code is in the model.py line 365
I change 
**`self.encoder.process_sparse[0].p0.spatial_size[k] = input_max_dim[k]`**
to
**`self.encoder.process_sparse[0].p0.spatial_size[k] = torch.tensor(input_max_dim[k])`**
As there is a type error when I use pytorch 1.3.
I use pytorch 1.3, cuda 10.2, python 3.6, SparseConvNet 2.0.
Could you give me any suggestions?  Thank you so much.

**Comment by XLechter** [comment]
Problem has been sovled when I use Pytorch1.4. It seems apart of functions in SparseConvNet are not  well supported by pytorch 1.3.

**Comment by santhu937** [comment]
@XLechter can u provide two test scenes, since I can't download test data of 45 + 58 GB

Thank You

**Comment by XLechter** [comment]
> @XLechter can u provide two test scenes, since I can't download test data of 45 + 58 GB
> 
> Thank You

The testset is so large, I am sorry I can not to upload it to google driver, but I find the download link in the repository is still availible.

**Comment by iyinlin** [comment]
Hello, excuse me, can you reproduce this paper? I'm a beginner and can't reproduce it
