### ISSUE TITLE
Testing on my own dataset.

### ISSUE THREAD

**Issue by XuyangBai** [angeladai/sgnn#7]
Hi @angeladai  Thanks a lot for your sharing. 

I would like to try your model on my own dataset which is also an indoor scene dataset. But I meet some problems during preparing the input since I do not have a Windows to use the code in GenerateScans. So I use the code from [here](https://github.com/andyzeng/tsdf-fusion-python) to compute the TSDF volume and change the [load_scene](https://github.com/angeladai/sgnn/blob/master/torch/data_util.py#L112) function accordingly to test on my own data.

I visualize the generated input mesh and predicted mesh and find that: 1. the input mesh looks quite different (much more sparse) from the mesh directly extract from the TSDF volume using marching cube. 2. the predicted mesh contains a big plane where it is empty in the input mesh. I suspect this situation is because my input preparation might have some mistake.

Could you provide some help? Thanks in advance.

**Comment by angeladai** [comment]
I'm not sure how much of the original GenerateScans code you're currently using. The windows-dependent part of that is the rendering, so the TSDF fusion can be re-used from there as well.

**Comment by XuyangBai** [comment]
Hi @angeladai  Thanks for your prompt reply.  

I am not using any code from `GenerateScans`. I  just compute TSDF volume using [tsdf-fusion](https://github.com/andyzeng/tsdf-fusion-python) and convert it to variables such as `locs` and `sdf` for testing. But the result is quite weird as I mentioned. So I think there might be some difference between the computation method of mine and yours (do you use truncated SDF or SDF? ).  Could you share your code for TSDF fusion? Or do you have some guess about the reason for my results?

Below are the meshes generated from marching cube over TSDF; and the two `.ply` file generated by running `test_scene.py`

<img width="634" alt="截屏2021-01-07 下午8 31 33" src="https://user-images.githubusercontent.com/15166089/103893014-7e54e780-5127-11eb-9d33-bbabc26b6628.png">
<img width="500" alt="截屏2021-01-07 下午8 31 53" src="https://user-images.githubusercontent.com/15166089/103893015-801eab00-5127-11eb-9d22-0a1425efdec7.png">
<img width="723" alt="截屏2021-01-07 下午8 32 29" src="https://user-images.githubusercontent.com/15166089/103893019-81e86e80-5127-11eb-827e-e16f0a06f9cc.png">

**Comment by Ademord** [comment]
@XuyangBai how were you able to fix this? i am starting to use tsdf-fusion as well to generate my scene's mesh and i was looking into this repo.

**Comment by ferbrjan** [comment]
I am facing the same problem with your SPSG paper, since I am unable to genrate the .sdf data that are required both here and in spsg. How to generate the .sdf files on my own dataset? 

Thank you,

**Comment by michalpolic** [comment]
Hello all, please, do you have any further information how to generate .sdf files which are presented in the scope of SPSG? How do you divide the input RGB-D frames into rooms and subsections of this rooms? Thank you in advance!

**Comment by angeladai** [comment]
All of our fusion was generated with [datagen/GenerateScans](https://github.com/angeladai/sgnn/tree/master/datagen/GenerateScans).

No room subsections are used, but Matterport3D contains annotations of its rooms out of the building captures.
