### ISSUE TITLE
Inference Requirements - Time and Memory

### ISSUE THREAD

**Issue by Magnusgaertner** [angeladai/sgnn#8]
Hi @angeladai thank you for sharing :) 

From your paper, I have two questions: 

- Do you have a rough estimate on inference time? I.e how long does one forward pass of a 64 x 64 x 128 volume at 2cm resolution take to process on your hardware. 

- Do you also have an estimate of how much memory is consumed while doing so?

Best regards and great work :+1: :tada: 
Magnus

**Comment by angeladai** [comment]
Forward pass for a 64x64x128 volume:
Since there are sparse convs the timing will vary noticeably depending on the amount of geometry, but something like ~0.5s (SparseConvNet hashes on the cpu, which takes quite some time), GPU memory ~1gb (running on a 2080).

**Comment by Magnusgaertner** [comment]
Hi @angeladai,

Thank you for your response :)

Best, Magnus :ok_hand:
