### ISSUE TITLE
Usage of 'GenerateScans'

### ISSUE THREAD

**Issue by bob292** [angeladai/sgnn#9]
Hello @angeladai ,

Thanks for sharing!

We are very interested in your project，and we want to try it on our own dataset.  I noticed that you've provided the 'GenrateScans' to create the .sdf files which suits for the project. But we ran into the same problem(https://github.com/angeladai/sgnn/issues/1) while implementing. So could you please explain a bit more about the usage of 'GenerateScans', for example the inputs' format and their meanings. Thanks in advance!

Bests,
Bob

**Comment by ferbrjan** [comment]
Same problem here.

I managed to run the generatescans VS project, but after that I am struggling to figure out what the inputs are. (I need the .sdf files in order to run your SPSG paper on my own dataset)

I do understand that the input should be some form of Matterport3D dataset, but I do not know which exact format of the dataset and I do not understand the mp_rooms_trainval.txt. Therefore if you could provide us with some examples and explanation, it would be extremely helpful.

Thank you very much,

Jan

**Comment by ferbrjan** [comment]
> Hello @angeladai ,
> 
> Thanks for sharing!
> 
> We are very interested in your project，and we want to try it on our own dataset. I noticed that you've provided the 'GenrateScans' to create the .sdf files which suits for the project. But we ran into the same problem(#1) while implementing. So could you please explain a bit more about the usage of 'GenerateScans', for example the inputs' format and their meanings. Thanks in advance!
> 
> Bests, Bob

Hello, 

If you have a look at the original issue , I made some progress regarding the .sdfs.reduced.ply error :-) You can try to do something similar to what I did and maybe we can manage to solve this! 

regards,

Jan

**Comment by bob292** [comment]
> > Hello @angeladai ,
> > Thanks for sharing!
> > We are very interested in your project，and we want to try it on our own dataset. I noticed that you've provided the 'GenrateScans' to create the .sdf files which suits for the project. But we ran into the same problem(#1) while implementing. So could you please explain a bit more about the usage of 'GenerateScans', for example the inputs' format and their meanings. Thanks in advance!
> > Bests, Bob
> 
> Hello,
> 
> If you have a look at the original issue , I made some progress regarding the .sdfs.reduced.ply error :-) You can try to do something similar to what I did and maybe we can manage to solve this!
> 
> regards,
> 
> Jan

Hi,

Bravo! Thanks to your progress we can finally create '.sdf' & '.kwn' files. =)

But as we all work with SPSG, and it's easy to notice that we need a '.colors' file which can't be created by the 'GenerateScans' to do the 3D inpainting with color. So do you have any idea on it?

Bests,
Bob

**Comment by ferbrjan** [comment]
> > > Hello @angeladai ,
> > > Thanks for sharing!
> > > We are very interested in your project，and we want to try it on our own dataset. I noticed that you've provided the 'GenrateScans' to create the .sdf files which suits for the project. But we ran into the same problem(#1) while implementing. So could you please explain a bit more about the usage of 'GenerateScans', for example the inputs' format and their meanings. Thanks in advance!
> > > Bests, Bob
> > 
> > 
> > Hello,
> > If you have a look at the original issue , I made some progress regarding the .sdfs.reduced.ply error :-) You can try to do something similar to what I did and maybe we can manage to solve this!
> > regards,
> > Jan
> 
> Hi,
> 
> Bravo! Thanks to your progress we can finally create '.sdf' & '.kwn' files. =)
> 
> But as we all work with SPSG, and it's easy to notice that we need a '.colors' file which can't be created by the 'GenerateScans' to do the 3D inpainting with color. So do you have any idea on it?
> 
> Bests, Bob

Hello,

unfortunately I have no clue on how to generate the .colors files. I assume those files contain the color depiction of each of the points of the point cloud, however I don't know in which format it is saved and how this filetype work. I will try to figure it out in the upcoming days.

If you make any progress please update me! :-)

**Comment by bob292** [comment]
Hello @angeladai,

Thanks a lot for your reply ! 

Just one more little question: As we are studying the project SPSG, we noticed that we need the '.colors' files to generate scences with color. Thus could you please inform us of their data format or how to generate them?

Bests,
Bob

**Comment by angeladai** [comment]
Since the colors are not relevant to sgnn, the data generation with colors is now on the spsg github: https://github.com/angeladai/spsg#data
the .colors files are similar to the geometry, storing sparse color information extracted at the sparse sdf locations.
